export const styles = {
  wrapper: {
    // Image ke background jaisa dark teal gradient
    background: "radial-gradient(circle, #1a4a5e 0%, #0d2836 100%)",
    minHeight: "100vh",
    width: "100%",
    fontFamily: '"Segoe UI", Roboto, Arial, sans-serif',
    paddingBottom: "60px",
  },
  header: {
    textAlign: "center",
    padding: "60px 20px",
  },
  headerTitle: {
    fontSize: "clamp(2rem, 8vw, 3.5rem)",
    margin: 0,
    color: "#ffffff",
    fontWeight: "800",
    letterSpacing: "-1px",
  },
  headerSubtitle: {
    fontSize: "1.2rem",
    color: "#ffffff",
    marginTop: "15px",
    opacity: 0.8,
    fontWeight: "400",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "30px",
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 25px",
  },
  card: {
    height: "260px",
    display: "flex",
    flexDirection: "column",
    borderRadius: "24px",
    overflow: "hidden",
    backgroundColor: "#161d2f",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    boxShadow: "0 20px 40px rgba(0,0,0,0.4)",
    transition: "transform 0.3s ease, border-color 0.3s ease",
    position: "relative",
  },
  cardHeader: {
    background: "rgba(255, 255, 255, 0.03)",
    color: "#4da3ff",
    padding: "20px 10px",
    textAlign: "center",
    fontWeight: "700",
    fontSize: "1.1rem",
    textTransform: "uppercase",
    letterSpacing: "1px",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  scrollArea: {
    flex: 1,
    overflow: "hidden",
  },
  descSlide: {
    width: "100%", // Ye slider ke total width ka part banega
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    boxSizing: "border-box",
  },
  contentBox: {
    textAlign: "center",
    padding: "20px",
  },
  dataName: {
    margin: 0,
    fontSize: "1.4rem",
    fontWeight: "600",
    color: "#ffffff",
    marginBottom: "10px",
  },
  amountBadge: {
    display: "inline-block",
    backgroundColor: "rgba(77, 163, 255, 0.15)",
    color: "#4da3ff",
    padding: "8px 20px",
    borderRadius: "50px",
    fontSize: "1.2rem",
    fontWeight: "700",
    border: "1px solid rgba(77, 163, 255, 0.3)",
  },
  currency: {
    fontSize: "0.9rem",
    marginRight: "2px",
    opacity: 0.8,
  },
  noData: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.4)",
    fontStyle: "italic",
  },
  dotsContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "6px",
    paddingBottom: "20px",
  },
  dot: {
    height: "6px",
    borderRadius: "10px",
    backgroundColor: "#4da3ff",
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  footerBar: {
    height: "6px",
    backgroundColor: "#1b75ff", // Login button blue
    position: "fixed",
    width: "100%",
    zIndex: 100,
  },
};
